theme: jekyll-theme-dinky
title: Africa Rising 
description: 
menu: [
{'name': 'Introduction', 'pagename': 'index'},
{'name': 'Data Collection', 'pagename': 'page1'},
{'name': 'Global Analysis', 'pagename': 'page2'},
{'name': 'Regional Analysis', 'pagename': 'page3'},
{'name': 'Network and Contingency', 'pagename': 'page4'},
{'name': 'Conclusion', 'pagename': 'page5'},
]
